export const types = {
    FETCH_ACTIVITIES: 'FETCH_ACTIVITIES',
    FETCH_ACTIVITY: 'FETCH_ACTIVITY',
    DELETE_ACTIVITY: 'DELETE_ACTIVITY',
    UPDATE_ACTIVITY: 'UPDATE_ACTIVITY',
    CREATE_ACTIVITY: 'CREATE_ACTIVITY',
    SET_CURRENT_ACTIVITY: 'SET_CURRENT_ACTIVITY',
};